-- Bootstrap database for CTFHost
BEGIN TRANSACTION;

-- Currently active sessions
CREATE TABLE sessions (
    session_id      VARCHAR(2000)   NOT NULL,
    username        VARCHAR(2000)   NOT NULL,
    expires         INTEGER         NOT NULL
);

-- Users and their information
CREATE TABLE users (
    username        VARCHAR(2000)   NOT NULL,
    password_hash   VARCHAR(2000)   NOT NULL,
    full_name       VARCHAR(2000)   NULL,
    email           VARCHAR(2000)   NULL,
    is_admin        BIT             DEFAULT 0
);

-- Add 'root' user with random password (will be generated by bootstrap_db.sh)
INSERT INTO users VALUES ("root", "@@_PASSWORD_HASH_@@", "Administrator", NULL, 1);

COMMIT;
