-- Bootstrap database for CTFHost
BEGIN TRANSACTION;

-- Currently active sessions
CREATE TABLE sessions (
    session_id_hash VARCHAR   NOT NULL UNIQUE,
    username        VARCHAR   NOT NULL,
    expires         INTEGER   NOT NULL
);

-- Users (teams) and their information
CREATE TABLE users (
    username        VARCHAR   NOT NULL UNIQUE,
    password_hash   VARCHAR   NOT NULL,
    full_name       VARCHAR   NULL,
    email           VARCHAR   NULL,
    is_admin        BIT       DEFAULT 0,
    token_seed      VARCHAR   NOT NULL
);

-- Flag submissions
CREATE TABLE submissions (
    team_name       VARCHAR   NOT NULL,
    task_id         INTEGER   NOT NULL,
    flag            VARCHAR   NOT NULL,
    correct         BIT       NOT NULL,
    points          INTEGER   NOT NULL,
    time            TIMESTAMP NOT NULL
);

-- Hint purchases
CREATE TABLE hint_purchases (
    task_id         INTEGER   NOT NULL,
    hint_hexid      VARCHAR   NOT NULL,
    team_name       VARCHAR   NOT NULL,
    cost            INTEGER   NOT NULL
);

-- Add 'root' user with random password (will be generated by bootstrap_db.sh)
INSERT INTO users VALUES ("root", "@@_PASSWORD_HASH_@@", "Administrator", NULL, 1, "@@_TOKEN_SEED_@@");

COMMIT;
