-- Bootstrap database for CTFHost
BEGIN TRANSACTION;

-- Currently active sessions
CREATE TABLE sessions (
    session_id      VARCHAR(2000)   NOT NULL,
    username        VARCHAR(2000)   NOT NULL,
    expires         INTEGER         NOT NULL
);

-- Users (teams) and their information
CREATE TABLE users (
    username        VARCHAR(2000)   NOT NULL,
    password_hash   VARCHAR(2000)   NOT NULL,
    full_name       VARCHAR(2000)   NULL,
    email           VARCHAR(2000)   NULL,
    is_admin        BIT             DEFAULT 0,
    token_seed      VARCHAR(200)    NOT NULL
);

-- Flag submissions
CREATE TABLE submissions (
    team_name       VARCHAR(2000)   NOT NULL,
    task_id         INTEGER         NOT NULL,
    flag            VARCHAR(2000)   NOT NULL,
    correct         BIT             NOT NULL,
    points          INTEGER         NOT NULL,
    time            TIMESTAMP       NOT NULL
);

-- Hint purchases
CREATE TABLE hint_purchases (
    task_id         INTEGER         NOT NULL,
    hint_hexid      VARCHAR(200)    NOT NULL,
    team_name       VARCHAR(2000)   NOT NULL,
    cost            INTEGER         NOT NULL
);

-- Add 'root' user with random password (will be generated by bootstrap_db.sh)
INSERT INTO users VALUES ("root", "@@_PASSWORD_HASH_@@", "Administrator", NULL, 1, "@@_TOKEN_SEED_@@");

COMMIT;
